apiVersion: v1
kind: Service
metadata:
  name: hello-admatic
  labels:
    app: hello-admatic
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-admatic
    tier: hello-admatic
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-admatic
  labels:
    app: hello-admatic
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-admatic
        tier: hello-admatic
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-admatic:latest
        name: hello-admatic
        ports:
        - containerPort: 80
          name: hello-admatic
